# Generated by Django 2.2.6 on 2022-12-26 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=1000)),
                ('prepare_mode', models.TextField(max_length=1000)),
                ('preparation_time', models.IntegerField()),
                ('portions', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
